# Generated by Django 4.2.21 on 2025-05-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GigReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_date', models.DateField()),
                ('highlight', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='gig_photos/')),
                ('review', models.TextField(max_length=2000)),
                ('review_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
        ),
    ]
