# Generated by Django 4.2.21 on 2025-05-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_reviews', '0002_artist_venue_alter_gigreview_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigreview',
            old_name='highlight',
            new_name='title',
        ),
    ]
