# Generated by Django 4.2.21 on 2025-05-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_reviews', '0003_rename_highlight_gigreview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='UK', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(default='https://www.example.com'),
        ),
    ]
