# Generated by Django 4.2.21 on 2025-05-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_reviews', '0006_alter_artist_logo_alter_gigreview_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gigreview',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='slug',
        ),
    ]
