# Generated by Django 4.2.21 on 2025-05-21 10:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_reviews', '0007_remove_artist_slug_remove_gigreview_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigreview',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
