# Generated by Django 4.2.21 on 2025-05-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_reviews', '0008_alter_gigreview_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='webbsite',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='webbsite',
            field=models.URLField(blank=True),
        ),
    ]
