# Generated by Django 4.2.21 on 2025-05-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_reviews', '0009_artist_webbsite_venue_webbsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='webbsite',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='webbsite',
            new_name='website',
        ),
    ]
