# Generated by Django 4.2.21 on 2025-05-28 10:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_reviews', '0010_rename_webbsite_artist_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
