# Generated by Django 4.2.21 on 2025-05-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_reviews', '0012_alter_venue_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigreview',
            name='review',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='gigreview',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
