# Generated by Django 4.2.21 on 2025-06-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig_reviews', '0013_alter_gigreview_review_alter_gigreview_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigreview',
            name='status',
        ),
        migrations.AlterField(
            model_name='gigreview',
            name='review',
            field=models.TextField(max_length=3000),
        ),
    ]
