# Generated by Django 4.2.21 on 2025-06-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_reviews', '0016_remove_profile_profile_photo_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigreview',
            old_name='photo',
            new_name='image',
        ),
    ]
