# Generated by Django 4.2.21 on 2025-06-11 12:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_reviews', '0017_rename_photo_gigreview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigreview',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
