# Generated by Django 4.2.21 on 2025-06-11 12:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig_reviews', '0018_alter_gigreview_image_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, default='red-horns_meorvq', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='gigreview',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='red-horns_meorvq', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='red-horns_meorvq', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, default='red-horns_meorvq', max_length=255, null=True, verbose_name='image'),
        ),
    ]
